version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.67.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./splunk-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # otlp
    depends_on:
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: otel
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data
